### ISSUE TITLE
Dynamical load of standard fonts for pdf creation?

### ISSUE THREAD

**Issue by Rotzbua** [blikblum/pdfmake-utils#1]
Hi,

is it possible to add standard fonts dynamically for pdf creation? (Browser)

I tested following script but it does not work:

```typescript
assetsLoader.registerFont({
    name: 'Courier',
    fileName: 'Courier',
    URL: 'assets/font/data/Courier.afm',
    styles: ['normal']
});
```

Error:

> ERROR Error: "File '../font/data/Courier.afm' not found in virtual file system"

It seems that the standard font are only stored in `pdfMake.rawFiles` and not processed further on.

**Comment by blikblum** [comment]
Sorry for late response. 
Standard fonts are working fine. See this [project](https://github.com/blikblum/pdfmake-playground/blob/master/src/setup/components.js). Times is a standard font. 

Are you using pdfmake-lite?

Can you share a small example that shows the fail?

**Comment by blikblum** [comment]
Probably you should be doing the following:

```
assetsLoader.load().then(() => {
        pdfMake.vfs = assetsLoader.vfs;
        pdfMake.fonts = assetsLoader.fonts;
        if (pdfMake.fs) {
          assetsLoader.rawFiles.forEach(file => {
            pdfMake.fs.writeFileSync(file.name, file.data);
          });
       }
})
```
You may be asking why: 
- pdfmake expects that the vfs property be a buffer or  a base64 encoded that is converted to a buffer, but pdfkit expects the standard font data to not be encoded
- by using pdfMake.fs.writeFileSync we bypass this conversion

**Comment by blikblum** [comment]
I released a new version and updated docs. Reopen if still having problems

**Comment by blikblum** [comment]
You can create a PR to pdfMake
