### ISSUE TITLE
pdfmake-lite bundling for 0.1.65

### ISSUE THREAD

**Issue by leo-pires** [blikblum/pdfmake-utils#15]
Hi, @blikblum . First, thanks for you awesome work with pdfmake-lite and pdfmake-utils.
We're using them on production and they helped us in reducing our bundle size.

I'm opening this issue over this repository because I didn't finded the proper repository for pdkmake-lite, so sorry by that. We noticed that pdfmake-lite is behind pdfmake by some versions, being 0.1.65 the last one.

Thanks!

**Comment by blikblum** [comment]
Sorry for the delay. I had to update a lot of packages.

I published version 0.1.66

Comes with other improvements like the ones from https://www.npmjs.com/package/pdfkit-next

The pdfmake-lite dev is done at https://github.com/blikblum/pdfmake/tree/lite
